### PR TITLE
Created templates for future release notes

### PR DESCRIPTION
**Pull request by dcdacosta**
This PR contains templates for future Release Notes updates. Templates with instructions at the top of each file are stored in the ../downstream/snippets directory.

### CODE REVIEW

**Comment by lmalivert** [comment]
LGTM @dcdacosta!

**Review by ianf77 — COMMENTED** [review]
A general comment. Where would we indicate documentation changes? For example new documents for 2.4, or when the Install Guide was split and Planning and Operations guide created. Or the addition of the Performance Guide. We ought to announce it somewhere.

**Comment by ariordan-redhat** [comment]
Would it make sense to move the release notes to the `downstream` folder, ie at the same level as `titles/`?  It might be out of scope for this work.

**Comment by jself-sudoku** [comment]
LGTM

**Comment by hherbly** [comment]
LGTM!

**Comment by emurtoug** [comment]
Would this template apply also to Z-Stream release notes? I'm thinking here of [AAP-5422](https://issues.redhat.com/browse/AAP-5422).

**Comment by dcdacosta** [comment]
> A general comment. Where would we indicate documentation changes? For example new documents for 2.4, or when the Install Guide was split and Planning and Operations guide created. Or the addition of the Performance Guide. We ought to announce it somewhere.

@ianf77 Good question; My original thinking was that this type of information could be added in a more ad-hoc fashion like I did for 2.3. I thought it might limit confusion by limiting the number of templates but maybe that's flawed and might cause doc change info to be missed. I'll go ahead and add a template.

**Comment by dcdacosta** [comment]
> Would it make sense to move the release notes to the `downstream` folder, ie at the same level as `titles/`? It might be out of scope for this work.

@ariordan-redhat I'm not sure if there was a specific reason for keeping it in a standalone directory? In my other projects, the release notes information was contained along side the other docs. Making this change might also allow us to use our attributes in the RN!?

**Comment by dcdacosta** [comment]
> Would this template apply also to Z-Stream release notes? I'm thinking here of [AAP-5422](https://issues.redhat.com/browse/AAP-5422).

@emurtoug I would say, for consistency sake, yes. You would just set the placeholder for version to the correct ZStream.

**Pull request merged**
