### PR TITLE
AAP-4882 Added link to the Pulp file system layout to Ch 2.2 Add'l resources

### PR DESCRIPTION
**Pull request by jself-sudoku**
In response to [AAP-4882](https://issues.redhat.com/browse/AAP-4882) - Added the following link to the Additional resources section after "Troubleshooting" topic: [Filesystem Layout](https://docs.pulpproject.org/pulpcore/installation/hardware-requirements.html#filesystem-layout).

### CODE REVIEW

**Comment by lmalivert** [comment]
Hi @jself-sudoku! It looks good to me. Is there a link to the Jira issue that you can share?

**Comment by jself-sudoku** [comment]
> Hi Lydie. Yes. I usually add that. Sorry!

**Comment by lmalivert** [comment]
Thank you! No worries :)

**Comment by jself-sudoku** [comment]
Thanks for the review! Not sure if I'll squash and merge yet until I hear back from the reporter. It's probably okay to merge, but just making sure. This didn't seem to need a technical review.

**Comment by lmalivert** [comment]
Yes, I saw the conversation in the Jira issue. It seems you fulfilled the request by adding a description of what the link is for. Let me know how you want to proceed :)

**Comment by jself-sudoku** [comment]
I think in the interest of time, we can proceed with squash and merge. Can you do this for me? Thanks in advance.

**Pull request merged**
