### PR TITLE
Update versions to AAP 2.2 and OCP 4.8

### PR DESCRIPTION
**Pull request by ianf77**
Changed platform version to 2.2

Update OpenShift Container Platform version compatibility

https://issues.redhat.com/browse/AAP-4837

### CODE REVIEW

**Comment by ianf77** [comment]
LGTM. I was just about to make the same change myself.

**Comment by ariordan-redhat** [comment]
@ianf77 
Do you think we should check (don't know who to ask, though) whether Openshift 4.7 is the minimum version for AAP 2.2?

**Review by ariordan-redhat — COMMENTED** [review]
LGTM, but should we confirm the minimum OCP version for AAP 2.2?

**Comment by ianf77** [comment]
Checked. It's 4.8

**Comment by ianf77** [comment]
Updated

**Review by ariordan-redhat — APPROVED** [review]
LGTM

**Review by ariordan-redhat — APPROVED** [review]
LGTM

**Comment by ariordan-redhat** [comment]
Version info taken from [Red Hat Ansible Automation Platform Life Cycle](https://access.redhat.com/support/policy/updates/ansible-automation-platform)

**Pull request merged**
