### PR TITLE
Add disclaimer for links to external sites

### PR DESCRIPTION
**Pull request by ariordan-redhat**
Add a file to the `downstream/snippets/` directory. It contains approved text that disclaims responsibility for the content in external websites.

### CODE REVIEW

**Review by ianf77 — APPROVED** [review]
LGTM. I might change a word or too, but it's legalese,  and that's opening a can of worms. If it's approved by legal, it's best stuck with.

**Review by dcdacosta — APPROVED** [review]
LGTM too. Thanks for adding this to the repo!

**Review by dcdacosta — APPROVED** [review]
This all lgtm. The info for adding the symlinks is very helpful. Maybe bold the term Disclaimer: ?

**Review by dcdacosta — APPROVED** [review]

**Review by emurtoug — COMMENTED** [review]
LGTM! That additional symlinks info is great; thank you, Aine!

**Pull request merged**
