### PR TITLE
Added default values of image.

### PR DESCRIPTION
**Pull request by ianf77**
Updated table with default values (normal and with RH RPM build.

Correct default value for EE_XXXX_IMAGE

https://issues.redhat.com/browse/AAP-8980

### CODE REVIEW

**Comment by simaishi** [comment]
@ianf77 For downstream documentation, do we actually document multiple ways to install ansible-builder, not just RPM?

**Comment by ianf77** [comment]
@simaishi I don't know. Who would be able to supply this information?

**Comment by simaishi** [comment]
https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.3/html/creating_and_consuming_execution_environments

Is this the only guide that talks about ansible-builder?

Regardless, for downstream, the only 'supported' way should be RPM. So I'm not actually sure if we really need to document quay at all... Please check with Phil.

**Comment by ianf77** [comment]
@simaishi 
According to Phil Griffiths quay is upstream only, downstream documents shouldn't mention it. How do you want to proceed here? Should the original statement be reworded to imply that RPM is the only supported installation method and that the value used with RPM is the default value?

**Comment by simaishi** [comment]
@ianf77 I think we can just add defalut value to existing explanation:

| `EE_BASE_IMAGE`
| Specifies the parent image for the automation execution environment, enabling a new image to be built that is based off of an already-existing image. This is typically a supported execution environment base image like ee-minimal or ee-supported, but it can also be an execution environment image that you've created previously and want to customize further. **The default value is 'registry.redhat.io/xxxxx'**.

I don't think we need to mention RPM or not at all, since that's the only supported way and that's the instruction in this guide.

**Comment by ianf77** [comment]
Corrections made.

**Comment by simaishi** [comment]
@ianf77 Just realized 'main' branch is for AAP 2.4, not 2.3.  So the path to the image is: `registry.redhat.io/ansible-automation-platform-24/xxx`.  Looks good otherwise.

**Comment by ianf77** [comment]
@simaishi 
The docs branch for 2.4 hasn't been created yet. It'll be created from main, but I can add an attribute which put the current version into the image.

**Comment by ianf77** [comment]
Actually we don't have an attribute which would replace 23 or 24. can I suggest <latest version> or <aap_version>?

**Comment by simaishi** [comment]
@ianf77 I'll leave it up to you.

**Review by ariordan-redhat — APPROVED** [review]
LGTM

**Pull request merged**
