### PR TITLE
Replace acme.org with example.com

### PR DESCRIPTION
**Pull request by ianf77**
Mainly in inventory file examples

[DDF] acme.org is not owned by Red Hat, please use example.com or similar, explicitly reserved for documentation, domains

https://issues.redhat.com/browse/AAP-13632

### CODE REVIEW

**Comment by evgeni** [comment]
There are still two mentions of `acme.org` in the files, but I have no idea where those are rendered:

```
% git grep acme\.
downstream/archive/archived-modules/platform/ref-external-existing-database.adoc:tower.acme.org
downstream/modules/platform/ref-standalone-hub-ext-database-inventory.adoc:data.acme.org
```

Otherwise LGTM!

**Comment by ianf77** [comment]
The one marked archive/ is in an archive folder as it's not used in any document. It can be ignored. Found the other file and fixing it now.

**Comment by evgeni** [comment]
that works for me :)

thanks ian!

**Review by emurtoug — COMMENTED** [review]
LGTM

**Pull request merged**
