### PR TITLE
2.3 AAP-9412 Add inventory file to snippets folder 

### PR DESCRIPTION
**Pull request by ariordan-redhat**
Add inventory file to snippets directory in 2.3 branch of AAP docs repo

Uses inventory file from the Ansible Automation Platform 2.3 Setup download. It's available from https://access.redhat.com/downloads/content/480/ver=2.3/rhel---9/2.3/x86_64/product-software

### CODE REVIEW

**Review by ianf77 — APPROVED** [review]
LGTM, although automationcatalog will probably disappear.

**Comment by lmalivert** [comment]
LGTM 👍🏽

**Comment by ariordan-redhat** [comment]
> LGTM, although automationcatalog will probably disappear.

This PR is only for 2.3 - I didn't add the inventory file to `main`. 
We'll have to create a PR to add a new inventory file to the `2.4` branch when 2.4 is released: I assume they'll have got rid of catalog by then.

**Comment by hherbly** [comment]
FWIW, LGTM.

**Comment by ariordan-redhat** [comment]
Infosec emailed about this file: they identified the `automationhub_ldap_bind_password = "GoodNewsEveryone" ` line as a potential breach.
I'll close this PR for the time being until we decide how to handle it.

**Pull request closed without merging**
